export const ToasterMessageConstants = {
  GENERAL_ERROR: 'Something went wrong',
  INCOMPLETE_FORM: 'Please complete the form',
  START_TEST: 'Best of luck for your test!',
  SUBMIT_TEST: 'Congratulations! Your test has been submitted',
  ERROR_STARTING_TEST: 'An error occured while generating test, Please try again.',
  ERROR_SUBMITTING_TEST: 'An error occured while submitting test, Please try again.',
  ERROR_ADDING_STUDENT: 'طالبعلم شامل کرتے وقت خرابی ہوئی۔',
  ERROR_UPDATING_STUDENT: 'طالبعلم کی تفصیل اپ ڈیٹ کرتے وقت خرابی ہوئی۔',
  ERROR_DELETING_STUDENT: 'طالبعلم حذف کرتے وقت خرابی ہوئی۔',
  ERROR_ADDING_LIBRARY_BOOK: 'کتاب شامل کرتے وقت خرابی آئی',
  ERROR_UPDATING_LIBRARY_BOOK: 'کتاب اپ ڈیٹ کرتے وقت خرابی آئی',
  ERROR_DELETING_LIBRARY_BOOK: 'کتاب حذف کرتے وقت خرابی آئی',
  ERROR_ADDING_LIBRARY_RECORD: 'ریکارڈ شامل کرتے وقت خرابی آئی',
  ERROR_UPDATING_LIBRARY_RECORD: 'ریکارڈ اپ ڈیٹ کرتے وقت خرابی آئی',
  ERROR_DELETING_LIBRARY_RECORD: 'ریکارڈ حذف کرتے وقت خرابی آئی',
};
